**Challange-1**

**Read the popular Iris dataset and split the dataset into 80:20 for tarining and testing after apply SVM with the following kernals**

**Linear**

**Polynomial Kernel**

**RBF(Gaussian Kernel)**

**Sigmoid**

In [1]:
import numpy as np
import pylab as pl
from sklearn import svm, datasets

In [2]:
iris = datasets.load_iris()
X = iris.data[:, :2]  
Y = iris.target

In [3]:
X.shape

(150, 2)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)

**Linear kernel**

In [5]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [6]:
y_pred = svclassifier.predict(X_test)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[8 0 0]
 [0 8 3]
 [0 4 7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.67      0.73      0.70        11
           2       0.70      0.64      0.67        11

    accuracy                           0.77        30
   macro avg       0.79      0.79      0.79        30
weighted avg       0.77      0.77      0.77        30



**Polynomial Kernel**

In [8]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [9]:
y_pred = svclassifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[8 0 0]
 [0 5 6]
 [0 2 9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.71      0.45      0.56        11
           2       0.60      0.82      0.69        11

    accuracy                           0.73        30
   macro avg       0.77      0.76      0.75        30
weighted avg       0.75      0.73      0.72        30



**RBF(Gaussian Kernel)**

In [11]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC()

In [13]:
y_pred = svclassifier.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[8 0 0]
 [0 8 3]
 [0 4 7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.67      0.73      0.70        11
           2       0.70      0.64      0.67        11

    accuracy                           0.77        30
   macro avg       0.79      0.79      0.79        30
weighted avg       0.77      0.77      0.77        30



**Sigmoid kernel**

In [15]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [16]:
y_pred = svclassifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
import warnings
warnings.filterwarnings("ignore")

[[ 8  0  0]
 [11  0  0]
 [11  0  0]]
              precision    recall  f1-score   support

           0       0.27      1.00      0.42         8
           1       0.00      0.00      0.00        11
           2       0.00      0.00      0.00        11

    accuracy                           0.27        30
   macro avg       0.09      0.33      0.14        30
weighted avg       0.07      0.27      0.11        30

